backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "works" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Works" # Used in the UI, ie.: "New Works"
    folder: "site/content/works" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Headline", name: "headline", widget: "string"}
      - {label: "Subheadline", name: "subheadline", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "process" 
    label: "Process" 
    folder: "site/content/process" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "YouTube Video ID", name: "youtubeVideoId", widget: "string", required: "true"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image 1216 × 762, name: image, widget: image}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Headline, name: headline, widget: string}
          - {label: Subheadline, name: subheadline, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Porfolio PDF", name: "portfolio_pdf", widget: "file", default: "site/uploads/portfolio.pdf"}
  - name: "component"
    label: "Components"
    files:
      - file: "site/data/footer.toml"
        label: "Footer"
        name: "footer"
        fields:
          - name: "params"
            label: "Params"
            widget: "object"
            fields:
              - {label: "Address1", name: "address1", widget: "string"}
              - {label: "Address2", name: "address2", widget: "string"}
              - {label: "Phone Number", name: "phonenumber", widget: "string"}
              - {label: "Email Address", name: "emailaddress", widget: "string"}
      - file: "site/data/socialmedia.toml"
        label: "Social Media Links"
        name: "socialmedia"
        fields:
          - name: "params"
            label: "Params"
            widget: "object"
            fields:
              - {label: "facebook", name: "facebook", widget: "string"}
              - {label: "twitter", name: "twitter", widget: "string"}
              - {label: "pinterest", name: "pinterest", widget: "string"}
              - {label: "reddit", name: "reddit", widget: "string"}
              - {label: "linkedin", name: "linkedin", widget: "string"}
              - {label: "tumblr", name: "tumblr", widget: "string"}